export const HOSPITAL_DATA = [
  {
    id: "1",
    name: "RS Jakarta",
    email: "rsjakarta@example.com",
    password: "hospitalpass123",
    address: "Jl. Sudirman No.1, Jakarta",
    phone: "02112345678",
    role: "hospital",
    bloodStock: [
      { bloodType: "A+", stock: 10 },
      { bloodType: "A-", stock: 5 },
      { bloodType: "B+", stock: 8 },
      { bloodType: "B-", stock: 4 },
      { bloodType: "O+", stock: 12 },
      { bloodType: "O-", stock: 6 },
      { bloodType: "AB+", stock: 7 },
      { bloodType: "AB-", stock: 3 },
    ],
  },
  {
    id: "2",
    name: "RS Surabaya",
    email: "rssurabaya@example.com",
    password: "hospitalpass456",
    address: "Jl. Ahmad Yani No.10, Surabaya",
    phone: "03198765432",
    role: "hospital",
    bloodStock: [
      { bloodType: "A+", stock: 9 },
      { bloodType: "A-", stock: 4 },
      { bloodType: "B+", stock: 6 },
      { bloodType: "B-", stock: 3 },
      { bloodType: "O+", stock: 10 },
      { bloodType: "O-", stock: 5 },
      { bloodType: "AB+", stock: 5 },
      { bloodType: "AB-", stock: 2 },
    ],
  },
  {
    id: "3",
    name: "RS Bandung",
    email: "rsbandung@example.com",
    password: "hospitalpass789",
    address: "Jl. Asia Afrika No.20, Bandung",
    phone: "02212345678",
    role: "hospital",
    bloodStock: [
      { bloodType: "A+", stock: 11 },
      { bloodType: "A-", stock: 6 },
      { bloodType: "B+", stock: 9 },
      { bloodType: "B-", stock: 3 },
      { bloodType: "O+", stock: 13 },
      { bloodType: "O-", stock: 7 },
      { bloodType: "AB+", stock: 6 },
      { bloodType: "AB-", stock: 2 },
    ],
  },
  {
    id: "4",
    name: "RS Medan",
    email: "rsmedan@example.com",
    password: "hospitalpass234",
    address: "Jl. Gatot Subroto No.3, Medan",
    phone: "06123456789",
    role: "hospital",
    bloodStock: [
      { bloodType: "A+", stock: 8 },
      { bloodType: "A-", stock: 4 },
      { bloodType: "B+", stock: 7 },
      { bloodType: "B-", stock: 2 },
      { bloodType: "O+", stock: 11 },
      { bloodType: "O-", stock: 5 },
      { bloodType: "AB+", stock: 5 },
      { bloodType: "AB-", stock: 3 },
    ],
  },
  {
    id: "5",
    name: "RS Makassar",
    email: "rsmakassar@example.com",
    password: "hospitalpass567",
    address: "Jl. Sultan Alauddin No.5, Makassar",
    phone: "04112345678",
    role: "hospital",
    bloodStock: [
      { bloodType: "A+", stock: 7 },
      { bloodType: "A-", stock: 5 },
      { bloodType: "B+", stock: 9 },
      { bloodType: "B-", stock: 3 },
      { bloodType: "O+", stock: 12 },
      { bloodType: "O-", stock: 6 },
      { bloodType: "AB+", stock: 8 },
      { bloodType: "AB-", stock: 2 },
    ],
  },
  {
    id: "6",
    name: "RS Malang",
    email: "rsmalang@example.com",
    password: "hospitalpass890",
    address: "Jl. Ijen No.12, Malang",
    phone: "03412345678",
    role: "hospital",
    bloodStock: [
      { bloodType: "A+", stock: 10 },
      { bloodType: "A-", stock: 5 },
      { bloodType: "B+", stock: 8 },
      { bloodType: "B-", stock: 4 },
      { bloodType: "O+", stock: 9 },
      { bloodType: "O-", stock: 3 },
      { bloodType: "AB+", stock: 7 },
      { bloodType: "AB-", stock: 1 },
    ],
  },
  {
    id: "7",
    name: "RS Bali",
    email: "rsbali@example.com",
    password: "hospitalpass012",
    address: "Jl. Denpasar No.8, Bali",
    phone: "036112345678",
    role: "hospital",
    bloodStock: [
      { bloodType: "A+", stock: 11 },
      { bloodType: "A-", stock: 6 },
      { bloodType: "B+", stock: 10 },
      { bloodType: "B-", stock: 4 },
      { bloodType: "O+", stock: 13 },
      { bloodType: "O-", stock: 7 },
      { bloodType: "AB+", stock: 9 },
      { bloodType: "AB-", stock: 2 },
    ],
  },
  {
    id: "8",
    name: "RS Semarang",
    email: "rssemarang@example.com",
    password: "hospitalpass345",
    address: "Jl. Pemuda No.10, Semarang",
    phone: "02412345678",
    role: "hospital",
    bloodStock: [
      { bloodType: "A+", stock: 9 },
      { bloodType: "A-", stock: 3 },
      { bloodType: "B+", stock: 8 },
      { bloodType: "B-", stock: 4 },
      { bloodType: "O+", stock: 12 },
      { bloodType: "O-", stock: 6 },
      { bloodType: "AB+", stock: 5 },
      { bloodType: "AB-", stock: 2 },
    ],
  },
  {
    id: "9",
    name: "RS Palembang",
    email: "rspalembang@example.com",
    password: "hospitalpass678",
    address: "Jl. Merdeka No.7, Palembang",
    phone: "07112345678",
    role: "hospital",
    bloodStock: [
      { bloodType: "A+", stock: 8 },
      { bloodType: "A-", stock: 4 },
      { bloodType: "B+", stock: 7 },
      { bloodType: "B-", stock: 2 },
      { bloodType: "O+", stock: 11 },
      { bloodType: "O-", stock: 5 },
      { bloodType: "AB+", stock: 6 },
      { bloodType: "AB-", stock: 1 },
    ],
  },
  {
    id: "10",
    name: "RS Yogyakarta",
    email: "rsyogyakarta@example.com",
    password: "hospitalpass901",
    address: "Jl. Malioboro No.6, Yogyakarta",
    phone: "027412345678",
    role: "hospital",
    bloodStock: [
      { bloodType: "A+", stock: 10 },
      { bloodType: "A-", stock: 5 },
      { bloodType: "B+", stock: 9 },
      { bloodType: "B-", stock: 3 },
      { bloodType: "O+", stock: 13 },
      { bloodType: "O-", stock: 6 },
      { bloodType: "AB+", stock: 7 },
      { bloodType: "AB-", stock: 2 },
    ],
  },
  {
    id: "11",
    name: "Rumah Sakit Waluyo Jati",
    email: "rswaluyo@example.com",
    password: "hospitalpass901",
    address: "Jl. Melon No.6, Karaksan",
    phone: "027412345678",
    role: "hospital",
    bloodStock: [
      { bloodType: "A+", stock: 10 },
      { bloodType: "A-", stock: 5 },
      { bloodType: "B+", stock: 9 },
      { bloodType: "B-", stock: 3 },
      { bloodType: "O+", stock: 13 },
      { bloodType: "O-", stock: 6 },
      { bloodType: "AB+", stock: 7 },
      { bloodType: "AB-", stock: 2 },
    ],
  },
];
