export const HOSPITAL_DATA = [
  {
    id: "1",
    name: "RS Jakarta",
    email: "rsjakarta@example.com",
    password: "hospitalpass123",
    address: "Jl. Sudirman No.1, Jakarta",
    phone: "02112345678",
    role: "hospital",
    bloodStock: [
      { bloodType: "A+", stock: 10 },
      { bloodType: "A-", stock: 5 },
      { bloodType: "B+", stock: 8 },
      { bloodType: "B-", stock: 4 },
      { bloodType: "O+", stock: 12 },
      { bloodType: "O-", stock: 6 },
      { bloodType: "AB+", stock: 7 },
      { bloodType: "AB-", stock: 3 },
    ],
  },
  {
    id: "2",
    name: "RS Surabaya",
    email: "rssurabaya@example.com",
    password: "hospitalpass456",
    address: "Jl. Ahmad Yani No.10, Surabaya",
    phone: "03198765432",
    role: "hospital",
    bloodStock: [
      { bloodType: "A+", stock: 9 },
      { bloodType: "A-", stock: 4 },
      { bloodType: "B+", stock: 6 },
      { bloodType: "B-", stock: 3 },
      { bloodType: "O+", stock: 10 },
      { bloodType: "O-", stock: 5 },
      { bloodType: "AB+", stock: 5 },
      { bloodType: "AB-", stock: 2 },
    ],
  },
  {
    id: "3",
    name: "RS Bandung",
    email: "rsbandung@example.com",
    password: "hospitalpass789",
    address: "Jl. Asia Afrika No.20, Bandung",
    phone: "02212345678",
    role: "hospital",
    bloodStock: [
      { bloodType: "A+", stock: 11 },
      { bloodType: "A-", stock: 6 },
      { bloodType: "B+", stock: 9 },
      { bloodType: "B-", stock: 3 },
      { bloodType: "O+", stock: 13 },
      { bloodType: "O-", stock: 7 },
      { bloodType: "AB+", stock: 6 },
      { bloodType: "AB-", stock: 2 },
    ],
  },
  {
    id: "4",
    name: "RS Medan",
    email: "rsmedan@example.com",
    password: "hospitalpass234",
    address: "Jl. Gatot Subroto No.3, Medan",
    phone: "06123456789",
    role: "hospital",
    bloodStock: [
      { bloodType: "A+", stock: 8 },
      { bloodType: "A-", stock: 4 },
      { bloodType: "B+", stock: 7 },
      { bloodType: "B-", stock: 2 },
      { bloodType: "O+", stock: 11 },
      { bloodType: "O-", stock: 5 },
      { bloodType: "AB+", stock: 5 },
      { bloodType: "AB-", stock: 3 },
    ],
  },
  {
    id: "5",
    name: "RS Makassar",
    email: "rsmakassar@example.com",
    password: "hospitalpass567",
    address: "Jl. Sultan Alauddin No.5, Makassar",
    phone: "04112345678",
    role: "hospital",
    bloodStock: [
      { bloodType: "A+", stock: 7 },
      { bloodType: "A-", stock: 5 },
      { bloodType: "B+", stock: 9 },
      { bloodType: "B-", stock: 3 },
      { bloodType: "O+", stock: 12 },
      { bloodType: "O-", stock: 6 },
      { bloodType: "AB+", stock: 8 },
      { bloodType: "AB-", stock: 2 },
    ],
  },
  {
    id: "6",
    name: "RS Malang",
    email: "rsmalang@example.com",
    password: "hospitalpass890",
    address: "Jl. Ijen No.12, Malang",
    phone: "03412345678",
    role: "hospital",
    bloodStock: [
      { bloodType: "A+", stock: 10 },
      { bloodType: "A-", stock: 5 },
      { bloodType: "B+", stock: 8 },
      { bloodType: "B-", stock: 4 },
      { bloodType: "O+", stock: 9 },
      { bloodType: "O-", stock: 3 },
      { bloodType: "AB+", stock: 7 },
      { bloodType: "AB-", stock: 1 },
    ],
  },
  {
    id: "7",
    name: "RS Bali",
    email: "rsbali@example.com",
    password: "hospitalpass012",
    address: "Jl. Denpasar No.8, Bali",
    phone: "036112345678",
    role: "hospital",
    bloodStock: [
      { bloodType: "A+", stock: 11 },
      { bloodType: "A-", stock: 6 },
      { bloodType: "B+", stock: 10 },
      { bloodType: "B-", stock: 4 },
      { bloodType: "O+", stock: 13 },
      { bloodType: "O-", stock: 7 },
      { bloodType: "AB+", stock: 9 },
      { bloodType: "AB-", stock: 2 },
    ],
  },
  {
    id: "8",
    name: "RS Semarang",
    email: "rssemarang@example.com",
    password: "hospitalpass345",
    address: "Jl. Pemuda No.10, Semarang",
    phone: "02412345678",
    role: "hospital",
    bloodStock: [
      { bloodType: "A+", stock: 9 },
      { bloodType: "A-", stock: 3 },
      { bloodType: "B+", stock: 8 },
      { bloodType: "B-", stock: 4 },
      { bloodType: "O+", stock: 12 },
      { bloodType: "O-", stock: 6 },
      { bloodType: "AB+", stock: 5 },
      { bloodType: "AB-", stock: 2 },
    ],
  },
  {
    id: "9",
    name: "RS Palembang",
    email: "rspalembang@example.com",
    password: "hospitalpass678",
    address: "Jl. Merdeka No.7, Palembang",
    phone: "07112345678",
    role: "hospital",
    bloodStock: [
      { bloodType: "A+", stock: 8 },
      { bloodType: "A-", stock: 4 },
      { bloodType: "B+", stock: 7 },
      { bloodType: "B-", stock: 2 },
      { bloodType: "O+", stock: 11 },
      { bloodType: "O-", stock: 5 },
      { bloodType: "AB+", stock: 6 },
      { bloodType: "AB-", stock: 1 },
    ],
  },
  {
    id: "10",
    name: "RS Yogyakarta",
    email: "rsyogyakarta@example.com",
    password: "hospitalpass901",
    address: "Jl. Malioboro No.6, Yogyakarta",
    phone: "027412345678",
    role: "hospital",
    bloodStock: [
      { bloodType: "A+", stock: 10 },
      { bloodType: "A-", stock: 5 },
      { bloodType: "B+", stock: 9 },
      { bloodType: "B-", stock: 3 },
      { bloodType: "O+", stock: 13 },
      { bloodType: "O-", stock: 6 },
      { bloodType: "AB+", stock: 7 },
      { bloodType: "AB-", stock: 2 },
    ],
  },
  {
    id: "11",
    name: "Rumah Sakit Waluyo Jati",
    email: "rswaluyo@example.com",
    password: "hospitalpass901",
    address: "Jl. Melon No.6, Karaksan",
    phone: "027412345678",
    role: "hospital",
    bloodStock: [
      { bloodType: "A+", stock: 10 },
      { bloodType: "A-", stock: 5 },
      { bloodType: "B+", stock: 9 },
      { bloodType: "B-", stock: 3 },
      { bloodType: "O+", stock: 13 },
      { bloodType: "O-", stock: 6 },
      { bloodType: "AB+", stock: 7 },
      { bloodType: "AB-", stock: 2 },
    ],
  },
];

export const PATIENT_DATA = [
  {
    id: "1",
    email: "john.doe@example.com",
    name: "John Doe",
    username: "johndoe123",
    password: "password123",
    phone: "123-456-7890",
    role: "patient",
  },
  {
    id: "2",
    email: "jane.smith@example.com",
    name: "Jane Smith",
    username: "janesmith456",
    password: "password456",
    phone: "234-567-8901",
    role: "patient",
  },
  {
    id: "3",
    email: "michael.jordan@example.com",
    name: "Michael Jordan",
    username: "mjordan23",
    password: "password789",
    phone: "345-678-9012",
    role: "patient",
  },
  {
    id: "4",
    email: "sarah.connor@example.com",
    name: "Sarah Connor",
    username: "sconnor999",
    password: "terminator123",
    phone: "456-789-0123",
    role: "patient",
  },
  {
    id: "5",
    email: "bruce.wayne@example.com",
    name: "Bruce Wayne",
    username: "batman001",
    password: "gotham456",
    phone: "567-890-1234",
    role: "patient",
  },
];

export const ORGANIZER_DATA = [
  {
    id: "1",
    name: "John Doe",
    role: "organizer",
    username: "johndoe",
    email: "johndoe@example.com",
    password: "password123",
    phone: "081234567890",
    postId: "101",
  },
  {
    id: "2",
    name: "Jane Smith",
    role: "organizer",
    username: "janesmith",
    email: "janesmith@example.com",
    password: "password456",
    phone: "082345678901",
    postId: "102",
  },
  {
    id: "3",
    name: "Emily Johnson",
    role: "organizer",
    username: "emilyjohnson",
    email: "emilyjohnson@example.com",
    password: "password789",
    phone: "083456789012",
    postId: "103",
  },
  {
    id: "4",
    name: "Michael Brown",
    role: "organizer",
    username: "michaelbrown",
    email: "michaelbrown@example.com",
    password: "password101",
    phone: "084567890123",
    postId: "104",
  },
  {
    id: "5",
    name: "Sarah Wilson",
    role: "organizer",
    username: "sarahwilson",
    email: "sarahwilson@example.com",
    password: "password202",
    phone: "085678901234",
    postId: "105",
  },
];

export const NAV_LINK = [
  {
    name: "community",
    href: "/community",
  },

  {
    name: "login/register",
    href: "/login",
  },
];

export const ROLES = [
  {
    role: "Pasien",
    href: "/register/patient",
  },
  {
    role: "Rumah Sakit",
    href: "/register/hospital",
  },
  {
    role: "Penyelenggara",
    href: "/register/organizer",
  },
];

export const POST = [
  {
    id: "1",
    creatorId: HOSPITAL_DATA[0].id,
    content: "Join us for a health awareness seminar!",
    timeAndDatePost: new Date("2024-10-20T10:00:00"),
    organizerName: HOSPITAL_DATA[0].name,
    regency: "Jakarta",
    province: "DKI Jakarta",
  },
  {
    id: "1",
    creatorId: HOSPITAL_DATA[0].id,
    content: "Join us for a health awareness seminar!",
    timeAndDatePost: new Date("2024-10-20T10:00:00"),
    organizerName: HOSPITAL_DATA[0].name,
    regency: "Jakarta",
    province: "DKI Jakarta",
  },
  {
    id: "1",
    creatorId: HOSPITAL_DATA[0].id,
    content: "Join us for a health awareness seminar!",
    timeAndDatePost: new Date("2024-10-20T10:00:00"),
    organizerName: HOSPITAL_DATA[0].name,
    regency: "Jakarta",
    province: "DKI Jakarta",
  },
  {
    id: "2",
    creatorId: ORGANIZER_DATA[1].id,
    content: "Blood donation drive happening this weekend.",
    timeAndDatePost: new Date("2024-10-22T09:00:00"),
    organizerName: ORGANIZER_DATA[1].name,
    regency: "Surabaya",
    province: "Jawa Timur",
  },
  {
    id: "3",
    creatorId: HOSPITAL_DATA[2].id,
    content: "Free health check-up for the community.",
    timeAndDatePost: new Date("2024-10-25T08:30:00"),
    organizerName: HOSPITAL_DATA[2].name,
    regency: "Bandung",
    province: "Jawa Barat",
  },
  {
    id: "4",
    creatorId: ORGANIZER_DATA[3].id,
    content: "Join us for a diabetes awareness workshop.",
    timeAndDatePost: new Date("2024-10-30T14:00:00"),
    organizerName: ORGANIZER_DATA[3].name,
    regency: "Medan",
    province: "Sumatera Utara",
  },
  {
    id: "5",
    creatorId: HOSPITAL_DATA[4].id,
    content: "Family health day with fun activities for all ages.",
    timeAndDatePost: new Date("2024-11-02T10:00:00"),
    organizerName: HOSPITAL_DATA[4].name,
    regency: "Makassar",
    province: "Sulawesi Selatan",
  },
  {
    id: "6",
    creatorId: HOSPITAL_DATA[5].id,
    content: "Wellness workshop focusing on nutrition and fitness.",
    timeAndDatePost: new Date("2024-11-05T11:00:00"),
    organizerName: HOSPITAL_DATA[5].name,
    regency: "Malang",
    province: "Jawa Timur",
  },
  {
    id: "7",
    creatorId: ORGANIZER_DATA[2].id,
    content: "Awareness campaign for mental health issues.",
    timeAndDatePost: new Date("2024-11-07T15:00:00"),
    organizerName: ORGANIZER_DATA[2].name,
    regency: "Bandung",
    province: "Jawa Barat",
  },
  {
    id: "8",
    creatorId: HOSPITAL_DATA[6].id,
    content: "Annual health fair with free screenings.",
    timeAndDatePost: new Date("2024-11-10T09:00:00"),
    organizerName: HOSPITAL_DATA[6].name,
    regency: "Bali",
    province: "Bali",
  },
  {
    id: "9",
    creatorId: ORGANIZER_DATA[0].id,
    content: "Health talk on the importance of vaccinations.",
    timeAndDatePost: new Date("2024-11-12T13:00:00"),
    organizerName: ORGANIZER_DATA[0].name,
    regency: "Yogyakarta",
    province: "DIY",
  },
  {
    id: "10",
    creatorId: HOSPITAL_DATA[7].id,
    content: "Join us for a fun run for health awareness.",
    timeAndDatePost: new Date("2024-11-15T07:00:00"),
    organizerName: HOSPITAL_DATA[7].name,
    regency: "Semarang",
    province: "Jawa Tengah",
  },
  {
    id: "11",
    creatorId: ORGANIZER_DATA[4].id,
    content: "Community clean-up and health check-up event.",
    timeAndDatePost: new Date("2024-11-17T09:00:00"),
    organizerName: ORGANIZER_DATA[4].name,
    regency: "Palembang",
    province: "Sumatera Selatan",
  },
  {
    id: "12",
    creatorId: HOSPITAL_DATA[8].id,
    content: "Health education seminar for seniors.",
    timeAndDatePost: new Date("2024-11-20T10:00:00"),
    organizerName: HOSPITAL_DATA[8].name,
    regency: "Jakarta",
    province: "DKI Jakarta",
  },
  {
    id: "13",
    creatorId: ORGANIZER_DATA[1].id,
    content: "Support group for chronic illness patients.",
    timeAndDatePost: new Date("2024-11-22T14:00:00"),
    organizerName: ORGANIZER_DATA[1].name,
    regency: "Surabaya",
    province: "Jawa Timur",
  },
  {
    id: "14",
    creatorId: HOSPITAL_DATA[9].id,
    content: "Fitness boot camp for the community.",
    timeAndDatePost: new Date("2024-11-25T08:00:00"),
    organizerName: HOSPITAL_DATA[9].name,
    regency: "Yogyakarta",
    province: "DIY",
  },
  {
    id: "15",
    creatorId: ORGANIZER_DATA[3].id,
    content: "Workshop on healthy cooking for families.",
    timeAndDatePost: new Date("2024-11-28T11:00:00"),
    organizerName: ORGANIZER_DATA[3].name,
    regency: "Medan",
    province: "Sumatera Utara",
  },
  {
    id: "16",
    creatorId: HOSPITAL_DATA[3].id,
    content: "Awareness program on heart health.",
    timeAndDatePost: new Date("2024-12-01T10:00:00"),
    organizerName: HOSPITAL_DATA[3].name,
    regency: "Medan",
    province: "Sumatera Utara",
  },
  {
    id: "17",
    creatorId: ORGANIZER_DATA[0].id,
    content: "Free workshop on first aid training.",
    timeAndDatePost: new Date("2024-12-03T12:00:00"),
    organizerName: ORGANIZER_DATA[0].name,
    regency: "Jakarta",
    province: "DKI Jakarta",
  },
  {
    id: "18",
    creatorId: HOSPITAL_DATA[1].id,
    content: "Health fair with expert talks and screenings.",
    timeAndDatePost: new Date("2024-12-05T09:00:00"),
    organizerName: HOSPITAL_DATA[1].name,
    regency: "Surabaya",
    province: "Jawa Timur",
  },
  {
    id: "19",
    creatorId: ORGANIZER_DATA[4].id,
    content: "Wellness retreat focusing on mental health.",
    timeAndDatePost: new Date("2024-12-07T09:00:00"),
    organizerName: ORGANIZER_DATA[4].name,

    regency: "Bali",
    province: "Bali",
  },
  {
    id: "20",
    creatorId: HOSPITAL_DATA[2].id,
    content: "Nutrition workshop with a guest speaker.",
    timeAndDatePost: new Date("2024-12-10T10:00:00"),
    organizerName: HOSPITAL_DATA[2].name,
    regency: "Bandung",
    province: "Jawa Barat",
  },
];
