export const HOSPITAL_DATA = [
  {
    nama: "RS Jakarta",
    email: "rsjakarta@example.com",
    password: "hospitalpass123",
    alamat: "Jl. Sudirman No.1, Jakarta",
    noTelpon: "02112345678",
    stokDarah: [
      { golDarah: "A+", stok: 10 },
      { golDarah: "A-", stok: 5 },
      { golDarah: "B+", stok: 8 },
      { golDarah: "B-", stok: 4 },
      { golDarah: "O+", stok: 12 },
      { golDarah: "O-", stok: 6 },
      { golDarah: "AB+", stok: 7 },
      { golDarah: "AB-", stok: 3 },
    ],
  },
  {
    nama: "RS Surabaya",
    email: "rssurabaya@example.com",
    password: "hospitalpass456",
    alamat: "Jl. Ahmad Yani No.10, Surabaya",
    noTelpon: "03198765432",
    stokDarah: [
      { golDarah: "A+", stok: 9 },
      { golDarah: "A-", stok: 4 },
      { golDarah: "B+", stok: 6 },
      { golDarah: "B-", stok: 3 },
      { golDarah: "O+", stok: 10 },
      { golDarah: "O-", stok: 5 },
      { golDarah: "AB+", stok: 5 },
      { golDarah: "AB-", stok: 2 },
    ],
  },
  {
    nama: "RS Bandung",
    email: "rsbandung@example.com",
    password: "hospitalpass789",
    alamat: "Jl. Asia Afrika No.20, Bandung",
    noTelpon: "02212345678",
    stokDarah: [
      { golDarah: "A+", stok: 11 },
      { golDarah: "A-", stok: 6 },
      { golDarah: "B+", stok: 9 },
      { golDarah: "B-", stok: 3 },
      { golDarah: "O+", stok: 13 },
      { golDarah: "O-", stok: 7 },
      { golDarah: "AB+", stok: 6 },
      { golDarah: "AB-", stok: 2 },
    ],
  },
  {
    nama: "RS Medan",
    email: "rsmedan@example.com",
    password: "hospitalpass234",
    alamat: "Jl. Gatot Subroto No.3, Medan",
    noTelpon: "06123456789",
    stokDarah: [
      { golDarah: "A+", stok: 8 },
      { golDarah: "A-", stok: 4 },
      { golDarah: "B+", stok: 7 },
      { golDarah: "B-", stok: 2 },
      { golDarah: "O+", stok: 11 },
      { golDarah: "O-", stok: 5 },
      { golDarah: "AB+", stok: 5 },
      { golDarah: "AB-", stok: 3 },
    ],
  },
  {
    nama: "RS Makassar",
    email: "rsmakassar@example.com",
    password: "hospitalpass567",
    alamat: "Jl. Sultan Alauddin No.5, Makassar",
    noTelpon: "04112345678",
    stokDarah: [
      { golDarah: "A+", stok: 7 },
      { golDarah: "A-", stok: 5 },
      { golDarah: "B+", stok: 9 },
      { golDarah: "B-", stok: 3 },
      { golDarah: "O+", stok: 12 },
      { golDarah: "O-", stok: 6 },
      { golDarah: "AB+", stok: 8 },
      { golDarah: "AB-", stok: 2 },
    ],
  },
  {
    nama: "RS Malang",
    email: "rsmalang@example.com",
    password: "hospitalpass890",
    alamat: "Jl. Ijen No.12, Malang",
    noTelpon: "03412345678",
    stokDarah: [
      { golDarah: "A+", stok: 10 },
      { golDarah: "A-", stok: 5 },
      { golDarah: "B+", stok: 8 },
      { golDarah: "B-", stok: 4 },
      { golDarah: "O+", stok: 9 },
      { golDarah: "O-", stok: 3 },
      { golDarah: "AB+", stok: 7 },
      { golDarah: "AB-", stok: 1 },
    ],
  },
  {
    nama: "RS Bali",
    email: "rsbali@example.com",
    password: "hospitalpass012",
    alamat: "Jl. Denpasar No.8, Bali",
    noTelpon: "036112345678",
    stokDarah: [
      { golDarah: "A+", stok: 11 },
      { golDarah: "A-", stok: 6 },
      { golDarah: "B+", stok: 10 },
      { golDarah: "B-", stok: 4 },
      { golDarah: "O+", stok: 13 },
      { golDarah: "O-", stok: 7 },
      { golDarah: "AB+", stok: 9 },
      { golDarah: "AB-", stok: 2 },
    ],
  },
  {
    nama: "RS Semarang",
    email: "rssemarang@example.com",
    password: "hospitalpass345",
    alamat: "Jl. Pemuda No.10, Semarang",
    noTelpon: "02412345678",
    stokDarah: [
      { golDarah: "A+", stok: 9 },
      { golDarah: "A-", stok: 3 },
      { golDarah: "B+", stok: 8 },
      { golDarah: "B-", stok: 4 },
      { golDarah: "O+", stok: 12 },
      { golDarah: "O-", stok: 6 },
      { golDarah: "AB+", stok: 5 },
      { golDarah: "AB-", stok: 2 },
    ],
  },
  {
    nama: "RS Palembang",
    email: "rspalembang@example.com",
    password: "hospitalpass678",
    alamat: "Jl. Merdeka No.7, Palembang",
    noTelpon: "07112345678",
    stokDarah: [
      { golDarah: "A+", stok: 8 },
      { golDarah: "A-", stok: 4 },
      { golDarah: "B+", stok: 7 },
      { golDarah: "B-", stok: 2 },
      { golDarah: "O+", stok: 11 },
      { golDarah: "O-", stok: 5 },
      { golDarah: "AB+", stok: 6 },
      { golDarah: "AB-", stok: 1 },
    ],
  },
  {
    nama: "RS Yogyakarta",
    email: "rsyogyakarta@example.com",
    password: "hospitalpass901",
    alamat: "Jl. Malioboro No.6, Yogyakarta",
    noTelpon: "027412345678",
    stokDarah: [
      { golDarah: "A+", stok: 10 },
      { golDarah: "A-", stok: 5 },
      { golDarah: "B+", stok: 9 },
      { golDarah: "B-", stok: 3 },
      { golDarah: "O+", stok: 13 },
      { golDarah: "O-", stok: 6 },
      { golDarah: "AB+", stok: 7 },
      { golDarah: "AB-", stok: 2 },
    ],
  },
  {
    nama: "Rumah Sakit Waluyo jati",
    email: "rswaluyo@example.com",
    password: "hospitalpass901",
    alamat: "Jl. Melon No.6, Karaksan",
    noTelpon: "027412345678",
    stokDarah: [
      { golDarah: "A+", stok: 10 },
      { golDarah: "A-", stok: 5 },
      { golDarah: "B+", stok: 9 },
      { golDarah: "B-", stok: 3 },
      { golDarah: "O+", stok: 13 },
      { golDarah: "O-", stok: 6 },
      { golDarah: "AB+", stok: 7 },
      { golDarah: "AB-", stok: 2 },
    ],
  },
];

export const NAV_LINK = [
  {
    name: "home",
    href: "/",
  },
  {
    name: "community",
    href: "/community",
  },
  {
    name: "about",
    href: "/about",
  },
  {
    name: "login/register",
    href: "/login",
  },
];

export const ROLES = [
  {
    role: "Pasien",
    href: "/register/patient",
  },
  {
    role: "Rumah Sakit",
    href: "/register/hospital",
  },
  {
    role: "Penyelenggara",
    href: "/register/organizer",
  },
];
