export const ORGANIZER_DATA = [
  {
    id: "1",
    name: "John Doe",
    role: "organizer",
    username: "johndoe",
    email: "johndoe@example.com",
    password: "password123",
    phone: "081234567890",
    postId: "101",
  },
  {
    id: "2",
    name: "Jane Smith",
    role: "organizer",
    username: "janesmith",
    email: "janesmith@example.com",
    password: "password456",
    phone: "082345678901",
    postId: "102",
  },
  {
    id: "3",
    name: "Emily Johnson",
    role: "organizer",
    username: "emilyjohnson",
    email: "emilyjohnson@example.com",
    password: "password789",
    phone: "083456789012",
    postId: "103",
  },
  {
    id: "4",
    name: "Michael Brown",
    role: "organizer",
    username: "michaelbrown",
    email: "michaelbrown@example.com",
    password: "password101",
    phone: "084567890123",
    postId: "104",
  },
  {
    id: "5",
    name: "Sarah Wilson",
    role: "organizer",
    username: "sarahwilson",
    email: "sarahwilson@example.com",
    password: "password202",
    phone: "085678901234",
    postId: "105",
  },
];
