export const PATIENT_DATA = [
  {
    id: "1",
    email: "john.doe@example.com",
    name: "John Doe",
    username: "johndoe123",
    password: "password123",
    phone: "123-456-7890",
    role: "patient",
  },
  {
    id: "2",
    email: "jane.smith@example.com",
    name: "Jane Smith",
    username: "janesmith456",
    password: "password456",
    phone: "234-567-8901",
    role: "patient",
  },
  {
    id: "3",
    email: "michael.jordan@example.com",
    name: "Michael Jordan",
    username: "mjordan23",
    password: "password789",
    phone: "345-678-9012",
    role: "patient",
  },
  {
    id: "4",
    email: "sarah.connor@example.com",
    name: "Sarah Connor",
    username: "sconnor999",
    password: "terminator123",
    phone: "456-789-0123",
    role: "patient",
  },
  {
    id: "5",
    email: "bruce.wayne@example.com",
    name: "Bruce Wayne",
    username: "batman001",
    password: "gotham456",
    phone: "567-890-1234",
    role: "patient",
  },
];
