import { HOSPITAL_DATA } from "./hospital";
import { ORGANIZER_DATA } from "./organizer";

export const POST = [
  {
    id: "1",
    creatorId: HOSPITAL_DATA[0].id,
    content: "Join us for a health awareness seminar!",
    timeAndDatePost: new Date("2024-10-20T10:00:00"),
    organizerName: HOSPITAL_DATA[0].name,
    regency: "Jakarta",
    province: "DKI Jakarta",
  },
  {
    id: "123123",
    creatorId: HOSPITAL_DATA[0].id,
    content: "Join us for a health awareness seminar!",
    timeAndDatePost: new Date("2024-10-20T10:00:00"),
    organizerName: HOSPITAL_DATA[0].name,
    regency: "Jakarta",
    province: "DKI Jakarta",
  },
  {
    id: "12321123",
    creatorId: HOSPITAL_DATA[0].id,
    content: "Join us for a health awareness seminar!",
    timeAndDatePost: new Date("2024-10-20T10:00:00"),
    organizerName: HOSPITAL_DATA[0].name,
    regency: "Jakarta",
    province: "DKI Jakarta",
  },
  {
    id: "2",
    creatorId: ORGANIZER_DATA[1].id,
    content: "Blood donation drive happening this weekend.",
    timeAndDatePost: new Date("2024-10-22T09:00:00"),
    organizerName: ORGANIZER_DATA[1].name,
    regency: "Surabaya",
    province: "Jawa Timur",
  },
  {
    id: "3",
    creatorId: HOSPITAL_DATA[2].id,
    content: "Free health check-up for the community.",
    timeAndDatePost: new Date("2024-10-25T08:30:00"),
    organizerName: HOSPITAL_DATA[2].name,
    regency: "Bandung",
    province: "Jawa Barat",
  },
  {
    id: "4",
    creatorId: ORGANIZER_DATA[3].id,
    content: "Join us for a diabetes awareness workshop.",
    timeAndDatePost: new Date("2024-10-30T14:00:00"),
    organizerName: ORGANIZER_DATA[3].name,
    regency: "Medan",
    province: "Sumatera Utara",
  },
  {
    id: "5",
    creatorId: HOSPITAL_DATA[4].id,
    content: "Family health day with fun activities for all ages.",
    timeAndDatePost: new Date("2024-11-02T10:00:00"),
    organizerName: HOSPITAL_DATA[4].name,
    regency: "Makassar",
    province: "Sulawesi Selatan",
  },
  {
    id: "6",
    creatorId: HOSPITAL_DATA[5].id,
    content: "Wellness workshop focusing on nutrition and fitness.",
    timeAndDatePost: new Date("2024-11-05T11:00:00"),
    organizerName: HOSPITAL_DATA[5].name,
    regency: "Malang",
    province: "Jawa Timur",
  },
  {
    id: "7",
    creatorId: ORGANIZER_DATA[2].id,
    content: "Awareness campaign for mental health issues.",
    timeAndDatePost: new Date("2024-11-07T15:00:00"),
    organizerName: ORGANIZER_DATA[2].name,
    regency: "Bandung",
    province: "Jawa Barat",
  },
  {
    id: "8",
    creatorId: HOSPITAL_DATA[6].id,
    content: "Annual health fair with free screenings.",
    timeAndDatePost: new Date("2024-11-10T09:00:00"),
    organizerName: HOSPITAL_DATA[6].name,
    regency: "Bali",
    province: "Bali",
  },
  {
    id: "9",
    creatorId: ORGANIZER_DATA[0].id,
    content: "Health talk on the importance of vaccinations.",
    timeAndDatePost: new Date("2024-11-12T13:00:00"),
    organizerName: ORGANIZER_DATA[0].name,
    regency: "Yogyakarta",
    province: "DIY",
  },
  {
    id: "10",
    creatorId: HOSPITAL_DATA[7].id,
    content: "Join us for a fun run for health awareness.",
    timeAndDatePost: new Date("2024-11-15T07:00:00"),
    organizerName: HOSPITAL_DATA[7].name,
    regency: "Semarang",
    province: "Jawa Tengah",
  },
  {
    id: "11",
    creatorId: ORGANIZER_DATA[4].id,
    content: "Community clean-up and health check-up event.",
    timeAndDatePost: new Date("2024-11-17T09:00:00"),
    organizerName: ORGANIZER_DATA[4].name,
    regency: "Palembang",
    province: "Sumatera Selatan",
  },
  {
    id: "12",
    creatorId: HOSPITAL_DATA[8].id,
    content: "Health education seminar for seniors.",
    timeAndDatePost: new Date("2024-11-20T10:00:00"),
    organizerName: HOSPITAL_DATA[8].name,
    regency: "Jakarta",
    province: "DKI Jakarta",
  },
  {
    id: "13",
    creatorId: ORGANIZER_DATA[1].id,
    content: "Support group for chronic illness patients.",
    timeAndDatePost: new Date("2024-11-22T14:00:00"),
    organizerName: ORGANIZER_DATA[1].name,
    regency: "Surabaya",
    province: "Jawa Timur",
  },
  {
    id: "14",
    creatorId: HOSPITAL_DATA[9].id,
    content: "Fitness boot camp for the community.",
    timeAndDatePost: new Date("2024-11-25T08:00:00"),
    organizerName: HOSPITAL_DATA[9].name,
    regency: "Yogyakarta",
    province: "DIY",
  },
  {
    id: "15",
    creatorId: ORGANIZER_DATA[3].id,
    content: "Workshop on healthy cooking for families.",
    timeAndDatePost: new Date("2024-11-28T11:00:00"),
    organizerName: ORGANIZER_DATA[3].name,
    regency: "Medan",
    province: "Sumatera Utara",
  },
  {
    id: "16",
    creatorId: HOSPITAL_DATA[3].id,
    content: "Awareness program on heart health.",
    timeAndDatePost: new Date("2024-12-01T10:00:00"),
    organizerName: HOSPITAL_DATA[3].name,
    regency: "Medan",
    province: "Sumatera Utara",
  },
  {
    id: "17",
    creatorId: ORGANIZER_DATA[0].id,
    content: "Free workshop on first aid training.",
    timeAndDatePost: new Date("2024-12-03T12:00:00"),
    organizerName: ORGANIZER_DATA[0].name,
    regency: "Jakarta",
    province: "DKI Jakarta",
  },
  {
    id: "18",
    creatorId: HOSPITAL_DATA[1].id,
    content: "Health fair with expert talks and screenings.",
    timeAndDatePost: new Date("2024-12-05T09:00:00"),
    organizerName: HOSPITAL_DATA[1].name,
    regency: "Surabaya",
    province: "Jawa Timur",
  },
  {
    id: "19",
    creatorId: ORGANIZER_DATA[4].id,
    content: "Wellness retreat focusing on mental health.",
    timeAndDatePost: new Date("2024-12-07T09:00:00"),
    organizerName: ORGANIZER_DATA[4].name,

    regency: "Bali",
    province: "Bali",
  },
  {
    id: "20",
    creatorId: HOSPITAL_DATA[2].id,
    content: "Nutrition workshop with a guest speaker.",
    timeAndDatePost: new Date("2024-12-10T10:00:00"),
    organizerName: HOSPITAL_DATA[2].name,
    regency: "Bandung",
    province: "Jawa Barat",
  },
];
